---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)
library(dslabs)
library(tidyverse)

#Read in data
titanic_train <- read.csv("C:/Users/Owner/Desktop/train.csv")
titanic_train
```



```{r}

titanic <- titanic_train %>%
  select(Survived, Pclass, Sex, Age, SibSp, Parch, Fare) %>%
  mutate(Survived = factor(Survived),
         Pclass = factor(Pclass),
         Sex = factor(Sex))

titanic
```

```{r}
titanic %>%  ggplot(aes(Age, fill = Survived)) +
  geom_density(aes(y = ..count..), alpha = 0.2, bw = 0.5, position = "stack") + facet_grid(Sex~Pclass)

```

```{r}

titanic %>%  ggplot(aes(Age, fill = Survived)) +
  geom_density(aes(y = ..count..), alpha = 0.2, bw = 0.5, position = "stack")


```

```{r}

titanic %>% ggplot(aes(Pclass, fill = Survived)) + geom_bar()



```

```{r}


titanic %>% filter(Fare >0) %>% 
  ggplot(aes(Survived, Fare, fill = Survived)) + scale_y_continuous(trans = "log2") +geom_boxplot() + geom_jitter(width = 0.1, alpha = 0.2) 

```

```{r}

second_survived <- count(titanic %>% filter(Pclass == 2, Survived == 1))
second_died <- count(titanic %>% filter(Pclass == 2,Survived == 0))


second_survived
second_died

100*(survived/891)
100*(died/891)
```
